import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../src/components/Layout";
import { getSortedPostsData } from "../lib/posts";

const Home: NextPage = ({ allPostsData }: any) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {allPostsData[0].title}
        {allPostsData[0].date}
        {allPostsData[0].id}
        {allPostsData[0].index}
        {allPostsData[0].content}
        <div dangerouslySetInnerHTML={{ __html: allPostsData[0].content }} />
      </Layout>
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}
